/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz;

import dbconnection.connectionprovider;
import java.awt.Dialog;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ABHISHEK TOMAR
 */
public class individual_marks extends javax.swing.JFrame {

    /**
     * Creates new form individual_marks
     */
    static String exam="C++";
    static String examname = "cppquizsummary";
    public individual_marks() {
        initComponents();
        if(exam=="C++")
        {
          examname = "cppquizsummary";  
        }
        
        if(exam=="DBMS")
        {
          examname = "dbmsquizsummary";  
        }
        if(exam=="JAVA")
        {
          examname = "javaquizsummary";  
        }
        if(exam=="C#")
        {
          examname = "cquizsummary";  
        }
        System.out.println(examname);
        topheadvar.setText("INDIVIDUAL STUDENT "+exam+ " MARKS");

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topheadvar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uservar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        uvar = new javax.swing.JTextField();
        utvar = new javax.swing.JTextField();
        atvar = new javax.swing.JTextField();
        cvar = new javax.swing.JTextField();
        ivar = new javax.swing.JTextField();
        mvar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(274, 217));
        setMinimumSize(new java.awt.Dimension(830, 325));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topheadvar.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        topheadvar.setText("INDIVIDUAL STUDENT MARKS");
        getContentPane().add(topheadvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("student username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 91, -1, -1));

        uservar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        uservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uservarActionPerformed(evt);
            }
        });
        uservar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uservarKeyPressed(evt);
            }
        });
        getContentPane().add(uservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 88, 175, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/search icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 88, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("STUDENT USERNAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("ATTEMPTED Q.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 177, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("UNATTEMPTED Q.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 177, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("CORRECT A.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 177, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("INCORRECT A.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 177, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("MARKS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 177, -1, -1));

        uvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(uvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 205, 182, -1));

        utvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(utvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 205, 80, -1));

        atvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        atvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atvarActionPerformed(evt);
            }
        });
        getContentPane().add(atvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 205, 80, -1));

        cvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(cvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 205, 80, -1));

        ivar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(ivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 205, 80, -1));

        mvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(mvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 205, 80, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/cancel.png"))); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atvarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username= uservar.getText();
        try
        {
            Connection con = connectionprovider.connector();
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("select * from "+examname+" where username='"+username+"'");
            if(rs.next()==true)
            {
                System.out.print("hello "+examname);
             ResultSet rs2 = st.executeQuery("select * from "+examname+" where username='"+username+"'");

                while(rs2.next())
                {
                    uvar.setText(rs2.getString(1));
                    atvar.setText(rs2.getString(2));
                    cvar.setText(rs2.getString(3));
                    ivar.setText(rs2.getString(4));
                    utvar.setText(rs2.getString(5));
                    mvar.setText(rs2.getString(6));


                }
            }
            
            else
            {
                JOptionPane p = new JOptionPane("No such username is found");
                  Dialog d = p.createDialog("Warning");
                  d.setAlwaysOnTop(true);
                  d.setVisible(true);
            }
        }
        catch(Exception e)
        {
             JOptionPane p = new JOptionPane("there is some problem please check your internet");
                  Dialog d = p.createDialog("Warning");
                  d.setAlwaysOnTop(true);
                  d.setVisible(true);
        System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void uservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uservarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uservarActionPerformed

    private void uservarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uservarKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        String username = uservar.getText();
        int length = username.length();
        
        
        if(Character.isLetter(c) || Character.isISOControl(c) || c>='0' && c<'9')
        {
           
            if(length<=11)
        {
            uservar.setEditable(true);
//            System.out.println(length);
        }
            
             else if(length>11)
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                uservar.setEditable(true);
                
            }
            
            else{
            uservar.setEditable(false);
               JOptionPane p = new JOptionPane("username should be in maximum 12 character");
                  Dialog d = p.createDialog("Warning");
                  d.setAlwaysOnTop(true);
                  d.setVisible(true);
            }
        }
//            uvar.setEditable(true);
            
        }
    }//GEN-LAST:event_uservarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(individual_marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(individual_marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(individual_marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(individual_marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new individual_marks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField atvar;
    private javax.swing.JTextField cvar;
    private javax.swing.JTextField ivar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField mvar;
    private javax.swing.JLabel topheadvar;
    private javax.swing.JTextField uservar;
    private javax.swing.JTextField utvar;
    private javax.swing.JTextField uvar;
    // End of variables declaration//GEN-END:variables
}
