/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz;

/**
 *
 * @author ABHISHEK TOMAR
 */

import java.sql.*;
import dbconnection.connectionprovider;
import java.awt.Dialog;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;



public class loginpage extends javax.swing.JFrame {

    /**
     * Creates new form loginpage
     */
    String exam2="";
    String tname="";
    String tsummary="";
    static int a=0;
    
    /*public class takevalue
    {
        public int tvalue(int a)
        {
            return a;
        }
    }*/
    
     
    
   
    public loginpage(String exam) {
        initComponents();
        
        exam2=exam;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        uvar = new javax.swing.JTextField();
        passvar = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(446, 224));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("GO QUIZ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(201, 201, 201))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("LOGIN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("username");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("password");

        uvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        uvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uvarActionPerformed(evt);
            }
        });
        uvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uvarKeyPressed(evt);
            }
        });

        passvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passvarActionPerformed(evt);
            }
        });
        passvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passvarKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/login-icon.png"))); // NOI18N
        jButton1.setText("login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/Clear-icon (1).png"))); // NOI18N
        jButton2.setText("clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/signup-icon-13.png"))); // NOI18N
        jButton3.setText("sign up");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("don't have an account");

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/cancel.png"))); // NOI18N
        jButton4.setText("cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passvar, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uvar, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(219, 219, 219))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel5)
                    .addComponent(jButton4))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         // TODO add your handling code here:
        String username = uvar.getText();
        String password = passvar.getText();
        
        if(username.equals("") || password.equals(""))
        {
            JOptionPane p = new JOptionPane("please fill all details");
            Dialog d = p.createDialog("Warning");
            d.setAlwaysOnTop(true);
            d.setVisible(true);
            
        }
        
        else
        {
            try
            {
               Connection conn = connectionprovider.connector();
               Statement st = conn.createStatement();
             
               ResultSet rs = st.executeQuery("select * from student where uname='"+username+"'");
               
               if(rs.next()==false)
               {
                  JOptionPane p = new JOptionPane("username is wrong");
                  Dialog d = p.createDialog("Warning");
                  d.setAlwaysOnTop(true);
                  d.setVisible(true);

               }
               
               else
               {
                   String pass = rs.getString(8);
                   String name = rs.getString(2);
                   if(password.equals(pass))
                           {
                               if(exam2.equals("C++ Quiz"))
                               {
                                  tname="cppmarks";
                                  tsummary="cppquizsummary";

                               }
                               
                              if(exam2.equals("Java Quiz"))
                               {
                                  tname="javamarks";
                                  tsummary="javaquizsummary";
                               }
                              
                              if(exam2.equals("DBMS Quiz"))
                               {
                                  tname="dbmsmarks";
                                  tsummary="dbmsquizsummary";

                               }
                              
                              if(exam2.equals("C# Quiz"))
                               {
                                  tname="cmarks";
                                  tsummary="cquizsummary";

                               }
                              
                             JOptionPane p2 = new JOptionPane("welcome "+rs.getString(7));
                             Dialog d =p2.createDialog("Message");
                             d.setAlwaysOnTop(true);
                             d.setVisible(true);
                               setVisible(false);
                               a=0;
                               quizselection.tvalue(a);
                               try
                               {
                                ResultSet r = st.executeQuery("select * from "+tname+" where username='"+username+"'");
                                if(r.next()==true)
                                { 
                                    //setVisible(false);
                                    
                                    int result = JOptionPane.showConfirmDialog(null,"you have already taken the quiz do you want to reattempt the quiz", "Message",
                                                                         JOptionPane.YES_NO_OPTION,
                                                                         JOptionPane.QUESTION_MESSAGE);
                                                     if(result == JOptionPane.YES_OPTION)
                                                     {
                                                        //Connection conn = connectionprovider.connector();
                                                         PreparedStatement p = conn.prepareStatement("delete from "+tsummary+" where username='"+username+"'");
                                                         //p.setString(1,username);
                                                         p.executeUpdate();
                                                         
                                                         /*PreparedStatement p2 = conn.prepareStatement("delete from cppmarks where username='"+username+"'");
                                                         p2.executeUpdate();*/
                                                         setVisible(false);
                                                         new quizselection().setVisible(false);
                                                         new instruction(username, name, exam2).setVisible(true);
                                                         }
                                                     else
                                                     {
                                                         setVisible(false);
                                                        new quizselection().setVisible(false);

                                                         new afterquizpage(username,tsummary).setVisible(true);
                                                     }
                                }
                                
                                else
                                {
                                  new quizselection().setVisible(false);

                                    instruction ip = new instruction(username, name, exam2);
                               ip.setVisible(true);
                                }
 
                               }
                               
                               catch(Exception e)
                               {
                                   JOptionPane p =new JOptionPane("sorry having problem in processing further");
                                   Dialog d2 = p.createDialog("Message");
                                   d2.setAlwaysOnTop(true);
                                   d2.setVisible(true);
                                   System.out.println(e);
                               }
                               
                               
                               
                           }
                   
                   else
                   {
                    JOptionPane p = new JOptionPane("password is incorrect");
                        Dialog d = p.createDialog("Warning");
                          d.setAlwaysOnTop(true);
                          d.setVisible(true);

                   }
               }
            }
            
            catch(Exception e)
            {
            JOptionPane p = new JOptionPane("sorry there is some error occuring please check your internet");
                  Dialog d = p.createDialog("Warning");
                  d.setAlwaysOnTop(true);
                  d.setVisible(true);
                System.out.println("this is the problem "+e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        //tvalue(a);
        a=2;
        quizselection.tvalue(a);
        signuppage sp=new signuppage();
        sp.setVisible(true);
       sp.setAlwaysOnTop(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        a=0;
        quizselection.tvalue(a);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         // TODO add your handling code here:
                   uvar.setText("");
                   passvar.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void uvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uvarActionPerformed

    private void uvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uvarKeyPressed
        // TODO add your handling code here:
       
       char c = evt.getKeyChar();
        
        String username = uvar.getText();
        int length = username.length();
        
        
        if(Character.isLetter(c) || Character.isISOControl(c) || c>='0' && c<'9')
        {
           
            if(length<=11)
        {
            uvar.setEditable(true);
//            System.out.println(length);
        }
            
             else if(length>11)
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                uvar.setEditable(true);
                
            }
            
            else{
            uvar.setEditable(false);
               JOptionPane p = new JOptionPane("username should be in maximum 12 character");
                  Dialog d = p.createDialog("Warning");
                  d.setAlwaysOnTop(true);
                  d.setVisible(true);
            }
        }
//            uvar.setEditable(true);
            
        }
        
//        else
//        {
//            usname.setEditable(false);
//            JOptionPane p = new JOptionPane("only letter is allowed");
//                  Dialog d = p.createDialog("Warning");
//                  d.setAlwaysOnTop(true);
//                  d.setVisible(true);
//        }
        
       
        
    }//GEN-LAST:event_uvarKeyPressed

    private void passvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passvarKeyPressed
        // TODO add your handling code here:
        String upass = passvar.getText();
        int length = upass.length();
        
        if(length<=9)
        {
            passvar.setEditable(true);
        }
            else
        {
            
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                passvar.setEditable(true);
                
            }
            else
            {
           passvar.setEditable(false);
           JOptionPane d = new JOptionPane("maximum 10 characters are allowed");
           Dialog p = d.createDialog("warning");
           p.setAlwaysOnTop(true);
           p.setVisible(true);
            }
        }
    }//GEN-LAST:event_passvarKeyPressed

    private void passvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new loginpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passvar;
    private javax.swing.JTextField uvar;
    // End of variables declaration//GEN-END:variables
}
