/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz;

import dbconnection.connectionprovider;
import java.awt.Dialog;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author ABHISHEK TOMAR
 */
public class question_append extends javax.swing.JFrame {

    /**
     * Creates new form question_append
     */String examname = "";
    public question_append(String exam) {
        initComponents();
        quesvar.setEditable(false);
        op1var.setEditable(false);
        op2var.setEditable(false);
        op3var.setEditable(false);
        op3var.setEditable(false);
        answervar.setEditable(false);


        if(exam=="C++")
        {
          examname = "cppquestion";
        }
        else if(exam=="Java")
        {
            examname="javaquestion";
        }
        else if(exam=="Dbms")
        {
            examname="dbmsquestion";
        }
        else if(exam=="C#")
            {
              examname = "cquestion";
             }
                topheadvar.setText(exam+ " EXAM QUESTION");

        
            try
            {
                Connection con = connectionprovider.connector();
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("select * from "+examname+" where sno='"+1+"'");
            while(rs.next())
            {
                quesvar.setText(rs.getString(2));
                op1var.setText(rs.getString(3));
                op2var.setText(rs.getString(4));
                op3var.setText(rs.getString(5));
                op4var.setText(rs.getString(6));
                answervar.setText(rs.getString(7));

            }
            }
            
            catch(Exception e)
            {
                JOptionPane p = new JOptionPane("there is some problem please check your internet");
                  Dialog d = p.createDialog("Warning");
                  d.setAlwaysOnTop(true);
                  d.setVisible(true);
                  System.out.println(e);
            }
        }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        qnovar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        quesvar = new javax.swing.JTextArea();
        op1var = new javax.swing.JTextField();
        op2var = new javax.swing.JTextField();
        op3var = new javax.swing.JTextField();
        op4var = new javax.swing.JTextField();
        answervar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        qvar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        editvar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        topheadvar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 100));
        setMinimumSize(new java.awt.Dimension(1378, 550));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("QUESTION  NO.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 96, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 144, -1, -1));

        qnovar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        qnovar.setText("1");
        getContentPane().add(qnovar, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 96, 20, -1));

        quesvar.setColumns(20);
        quesvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quesvar.setRows(5);
        jScrollPane1.setViewportView(quesvar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 128, 584, -1));

        op1var.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        op1var.setText("OPTION 1");
        getContentPane().add(op1var, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 249, 387, -1));

        op2var.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        op2var.setText("OPTION 2 ");
        getContentPane().add(op2var, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 305, 387, -1));

        op3var.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        op3var.setText("OPTION 3");
        getContentPane().add(op3var, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 361, 387, -1));

        op4var.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        op4var.setText("OPTION 4");
        getContentPane().add(op4var, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 416, 387, -1));

        answervar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        answervar.setText("ANSWER");
        getContentPane().add(answervar, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 472, 387, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("QUESTION NO.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 309, -1, 28));

        qvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        qvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qvarActionPerformed(evt);
            }
        });
        qvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qvarKeyPressed(evt);
            }
        });
        getContentPane().add(qvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1006, 309, 102, 28));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/search icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1126, 309, -1, -1));

        editvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/edit.png"))); // NOI18N
        editvar.setText("EDIT");
        editvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editvarActionPerformed(evt);
            }
        });
        getContentPane().add(editvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 420, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/cancel.png"))); // NOI18N
        jButton3.setText("CANCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1055, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("OPTION 1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 252, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("OPTION 2");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 308, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("OPTION 3");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 364, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("OPTION 4");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 419, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("ANSWER");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 472, -1, 22));

        topheadvar.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        topheadvar.setText("EXAM QUESTION ");
        getContentPane().add(topheadvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/background_image.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String number ="";
                number = qvar.getText();
        int number2 = Integer.parseInt(number);
        
        if(number=="")
        {
            JOptionPane p = new JOptionPane("please type something");
                  Dialog d = p.createDialog("Warning");
                  d.setAlwaysOnTop(true);
                  d.setVisible(true);
        }
        else if(number2>=1 && number2<=20)
        {
            qnovar.setText(number);
        try
        {
           Connection con = connectionprovider.connector();
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("select * from "+examname+" where sno='"+number+"'"); 
             while(rs.next())
            {
                quesvar.setText(rs.getString(2));
                op1var.setText(rs.getString(3));
                op2var.setText(rs.getString(4));
                op3var.setText(rs.getString(5));
                op4var.setText(rs.getString(6));
                answervar.setText(rs.getString(7));

            }
        }
        
        catch(Exception e)
        {
            JOptionPane p = new JOptionPane("there is some problem please check your internet");
                  Dialog d = p.createDialog("Warning");
                  d.setAlwaysOnTop(true);
                  d.setVisible(true);
                  System.out.println(e);
        }
        
        }
        else
        {
            JOptionPane p = new JOptionPane("please type appropriate question number to search");
                  Dialog d = p.createDialog("Warning");
                  d.setAlwaysOnTop(true);
                  d.setVisible(true);
                  
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        question_details.open=0;
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void editvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editvarActionPerformed
        // TODO add your handling code here:
        String question="", option1="", option2="", option3="", option4="", answer="";
        if(editvar.getText().equals("EDIT"))
            
        {
            editvar.setText("UPDATE");
            quesvar.setEditable(true);
            op1var.setEditable(true);
            op2var.setEditable(true);
            op3var.setEditable(true);
            op4var.setEditable(true);
            answervar.setEditable(true);
        }
        else if(editvar.getText().equals("UPDATE"))
        {
            question=quesvar.getText();
            option1 = op1var.getText();
            option2 = op2var.getText();
            option3 = op3var.getText();
            option4 = op4var.getText();
            answer = answervar.getText();
            String number= qnovar.getText();
            
            if(question.equals("") || option1.equals("") || option2.equals("") || option3.equals("") || option4.equals("") || answer.equals(""))
            {
                  JOptionPane p = new JOptionPane("please all the fields");
                  Dialog d = p.createDialog("Warning");
                  d.setAlwaysOnTop(true);
                  d.setVisible(true);
            }
            else
            {
                
            
            try
            {
                 Connection con = connectionprovider.connector();
                   Statement st = con.createStatement();
                   
                   PreparedStatement p = con.prepareStatement("update "+examname+" set question= '"+question+"', option1='"+option1+"', option2='"+option2+"', option3='"+option3+"', option4='"+option4+"', answer='"+answer+"' where sno='"+number+"'");
                   p.executeUpdate();
                   
                   JOptionPane p2 = new JOptionPane("record updated sucessfully",JOptionPane.INFORMATION_MESSAGE);
                    JDialog d = p2.createDialog("Message");
                         d.setAlwaysOnTop(true);
                     d.setVisible(true);
                     editvar.setText("EDIT");
                     quesvar.setEditable(false);
                         op1var.setEditable(false);
                         op2var.setEditable(false);
                        op3var.setEditable(false);
                        op4var.setEditable(false);
                         answervar.setEditable(false);
            }
            catch(Exception e)
            {
                JOptionPane p2 = new JOptionPane("some error occured while updating...",JOptionPane.INFORMATION_MESSAGE);
                    JDialog d = p2.createDialog("Message");
                         d.setAlwaysOnTop(true);
                     d.setVisible(true);
                     System.out.print("error is "+e);
            }
            }
        }
    }//GEN-LAST:event_editvarActionPerformed

    private void qvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qvarKeyPressed
        // TODO add your handling code here:
        int length = qvar.getText().length();
        char c = evt.getKeyChar();
        
        if(length<2)
        {
            if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
            {
              qvar.setEditable(true);   
            }
            else
            {
                
                if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
                    {
                       qvar.setEditable(true); 
                    }
                
                else if(Character.isLetter(c)){
                qvar.setEditable(false);
                 JOptionPane p2 = new JOptionPane("only number is allowed",JOptionPane.INFORMATION_MESSAGE);
                    JDialog d = p2.createDialog("Warning");
                         d.setAlwaysOnTop(true);
                     d.setVisible(true);
                }
            }
        }
        
        else if(length>=2)
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
                    {
                       qvar.setEditable(true); 
                    }
            
            else
            {
                qvar.setEditable(false); 
                JOptionPane p2 = new JOptionPane("maximum 2 digit",JOptionPane.INFORMATION_MESSAGE);
                    JDialog d = p2.createDialog("Warning");
                         d.setAlwaysOnTop(true);
                     d.setVisible(true);
            }
        }
    }//GEN-LAST:event_qvarKeyPressed

    private void qvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(question_append.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(question_append.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(question_append.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(question_append.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new question_append().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answervar;
    private javax.swing.JButton editvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField op1var;
    private javax.swing.JTextField op2var;
    private javax.swing.JTextField op3var;
    private javax.swing.JTextField op4var;
    private javax.swing.JLabel qnovar;
    private javax.swing.JTextArea quesvar;
    private javax.swing.JTextField qvar;
    private javax.swing.JLabel topheadvar;
    // End of variables declaration//GEN-END:variables
}
