/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz;

import dbconnection.connectionprovider;
import java.awt.Dialog;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ABHISHEK TOMAR
 */
public class rankpage extends javax.swing.JFrame {

    /**
     * Creates new form rankpage
     */
    static String status="hide search and back button";
    public static void getvalue(String statusref)
    {
        status = statusref;
    }

    String tname="";
    public rankpage() {
        initComponents();
        if(status=="hide search and back button")
        {
            searchvar.setVisible(false);
            backvar.setVisible(false);
            homevar.setVisible(true);
        }
        
        else if(status=="show search and back button")
        {
            searchvar.setVisible(true);
            backvar.setVisible(true);
            homevar.setVisible(false);

        }
        
        try
        {
            namevar.setText("C++ RANK");
            Connection con = connectionprovider.connector();
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("select * from cppmarks");
            
            tablevar.setAutoResizeMode(tablevar.AUTO_RESIZE_OFF);
            tablevar.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            /* tablevar.setModel(new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
            return false;
            }
            });*/
            //tablevar.isCellEditable(false);
            // tablevar.setEditable(false);
        }
    
    catch(Exception e)
    {
        JOptionPane p = new JOptionPane("there is some problem please check your internet");
                  Dialog d = p.createDialog("Warning");
                  d.setAlwaysOnTop(true);
                  d.setVisible(true);
        System.out.println(e);
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        namevar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablevar = new javax.swing.JTable();
        homevar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        searchvar = new javax.swing.JButton();
        backvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("GO QUIZ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(544, 544, 544)
                .addComponent(jLabel1)
                .addContainerGap(690, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C++", "JAVA", "DBMS", "C#" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 106, -1, -1));

        namevar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        namevar.setForeground(new java.awt.Color(242, 242, 242));
        namevar.setText("C++ RANK");
        getContentPane().add(namevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 105, -1, -1));

        tablevar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tablevar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablevar.setEnabled(false);
        tablevar.setPreferredSize(new java.awt.Dimension(1372, 530));
        jScrollPane1.setViewportView(tablevar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1370, 530));

        homevar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        homevar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/homeicon.png"))); // NOI18N
        homevar.setText("HOME");
        homevar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homevarActionPerformed(evt);
            }
        });
        getContentPane().add(homevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 698, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        searchvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/search icon.png"))); // NOI18N
        searchvar.setText("SEARCH INDIVIDUAL STUDENT MARKS");
        searchvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchvarActionPerformed(evt);
            }
        });
        getContentPane().add(searchvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 700, -1, -1));

        backvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backvar.setText("BACK");
        backvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backvarActionPerformed(evt);
            }
        });
        getContentPane().add(backvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 700, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/afterpage.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
         if(jComboBox1.getSelectedItem().equals("C++"))
        {
            namevar.setText("C++ Rank");
            tname="cppmarks";
        }
         
         if(jComboBox1.getSelectedItem().equals("JAVA"))
         {
            namevar.setText("Java Rank");
            tname="javamarks";
         }
         
         if(jComboBox1.getSelectedItem().equals("DBMS"))
         {
             namevar.setText("DBMS Rank");
             tname="dbmsmarks";
         }
         
         if(jComboBox1.getSelectedItem().equals("C#"))
         {
            namevar.setText("C# Rank");
            tname="cmarks";
         }
             try
        {
            Connection con = connectionprovider.connector();
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("select * from "+tname+"");
            
            tablevar.setAutoResizeMode(tablevar.AUTO_RESIZE_OFF);
            tablevar.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            /* tablevar.setModel(new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
            return false;
            }
            });*/
            //tablevar.isCellEditable(false);
            //tablevar.setEditable(false);
        }
    
    catch(Exception e)
    {
        System.out.println(e);
    }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void homevarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homevarActionPerformed
        // TODO add your handling code here:
       
        new firstpage().setVisible(true);
         setVisible(false);
    }//GEN-LAST:event_homevarActionPerformed

    private void backvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backvarActionPerformed
        // TODO add your handling code here:
        
        status="hide search and back button";
        new Admin_first_page().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backvarActionPerformed

    private void searchvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchvarActionPerformed
        // TODO add your handling code here:
        String examname = (String) jComboBox1.getSelectedItem();
        individual_marks.exam = examname;
        new individual_marks().setVisible(true);
    }//GEN-LAST:event_searchvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rankpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rankpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rankpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rankpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rankpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backvar;
    private javax.swing.JButton homevar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namevar;
    private javax.swing.JButton searchvar;
    private javax.swing.JTable tablevar;
    // End of variables declaration//GEN-END:variables
}
