/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz;

import dbconnection.connectionprovider;
import java.awt.Dialog;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author ABHISHEK TOMAR
 */
public class student_personal_details extends javax.swing.JFrame {

    /**
     * Creates new form student_personal_details
     */
    public student_personal_details(String username) {
        initComponents();
        fvar.setEditable(false);
        lvar.setEditable(false);
        avar.setEditable(false);
        gvar.setEditable(false);
        qvar.setEditable(false);
        uvar.setEditable(false);
        try
        {
            Connection con = connectionprovider.connector();
        Statement st = con.createStatement();
        
        ResultSet rs = st.executeQuery("select * from student where uname='"+username+"'");
        while(rs.next())
        {
            fvar.setText(rs.getString(2));
            lvar.setText(rs.getString(3));
            avar.setText(rs.getString(4));
            gvar.setText(rs.getString(5));
            qvar.setText(rs.getString(6));
            uvar.setText(rs.getString(7));
        }
        }
        
        catch(Exception e)
        {
            JOptionPane p = new JOptionPane("Sorry some errro has occured please check your connection");
                     JDialog d = p.createDialog("Warning");
                    d.setVisible(true);
                     d.setAlwaysOnTop(true);
                     System.out.print("error is "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fvar = new javax.swing.JTextField();
        lvar = new javax.swing.JTextField();
        avar = new javax.swing.JTextField();
        gvar = new javax.swing.JTextField();
        qvar = new javax.swing.JTextField();
        uvar = new javax.swing.JTextField();
        editbutton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1378, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("GO QUIZ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(615, 615, 615)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel2.setText("STUDENT PERSONAL DETAILS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 139, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("FIRST NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("LAST NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("AGE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("GENDER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setText("QUALIFICATION");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("USERNAME");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 680, -1, -1));

        fvar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        fvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fvarKeyPressed(evt);
            }
        });
        getContentPane().add(fvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 270, -1));

        lvar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lvarKeyPressed(evt);
            }
        });
        getContentPane().add(lvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 270, -1));

        avar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        avar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avarActionPerformed(evt);
            }
        });
        avar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                avarKeyPressed(evt);
            }
        });
        getContentPane().add(avar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 270, -1));

        gvar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        gvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gvarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gvarKeyReleased(evt);
            }
        });
        getContentPane().add(gvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 270, -1));

        qvar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        qvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qvarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qvarKeyReleased(evt);
            }
        });
        getContentPane().add(qvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 270, -1));

        uvar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        uvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uvarKeyPressed(evt);
            }
        });
        getContentPane().add(uvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 680, 270, -1));

        editbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/edit.png"))); // NOI18N
        editbutton.setText("EDIT");
        editbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(editbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 690, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/cancel.png"))); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 690, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Admin_first_page().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void editbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbuttonActionPerformed
        // TODO add your handling code here:
                   String first_name="", last_name="", age="", gender="", qualification="", username="";

        if(editbutton.getText().equals("EDIT"))
        {
                  editbutton.setText("UPDATE");

        fvar.setEditable(true);
        lvar.setEditable(true);
        avar.setEditable(true);
        gvar.setEditable(true);
        qvar.setEditable(true);
        uvar.setEditable(true);
        
//         private javax.swing.JTextField g2var;
//        gvar = new javax.swing.jComboBox1();
        
         
        }
        else if(editbutton.getText().equals("UPDATE"))
        {
            first_name = fvar.getText();
         last_name = lvar.getText();
         age = avar.getText();
         gender = gvar.getText();
         qualification = qvar.getText();
         username = uvar.getText();
            
         if(first_name.equals("") || last_name.equals("") || age.equals("") || gender.equals("") || qualification.equals("") || username.equals(""))
        
         {
             JOptionPane p = new JOptionPane("please fill all the details",JOptionPane.INFORMATION_MESSAGE);
            JDialog d = p.createDialog("Warning");
            d.setAlwaysOnTop(true);
            d.setVisible(true);

         }
         else
         {
             editbutton.setText("EDIT");
             fvar.setEditable(false);
        lvar.setEditable(false);
        avar.setEditable(false);
        gvar.setEditable(false);
        qvar.setEditable(false);
        uvar.setEditable(false);
             
             try
             {
                  Connection con = connectionprovider.connector();
                   Statement st = con.createStatement();
                   
                   PreparedStatement p = con.prepareStatement("update student set fname= '"+first_name+"', lname='"+last_name+"', age='"+age+"', gender='"+gender+"', qualification='"+qualification+"', uname='"+username+"' where uname='"+username+"'");
                   p.executeUpdate();
                   
                   JOptionPane p2 = new JOptionPane("record updated sucessfully",JOptionPane.INFORMATION_MESSAGE);
                    JDialog d = p2.createDialog("Message");
                         d.setAlwaysOnTop(true);
                     d.setVisible(true);
             }
             
             catch(Exception e)
             {
                 JOptionPane p = new JOptionPane("error occured in updating record",JOptionPane.INFORMATION_MESSAGE);
            JDialog d = p.createDialog("Warning");
            d.setAlwaysOnTop(true);
            d.setVisible(true);
            System.out.print("error is "+e);
             }
         }
        }
    }//GEN-LAST:event_editbuttonActionPerformed

    private void avarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_avarActionPerformed

    private void avarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_avarKeyPressed
        // TODO add your handling code here:
         int length = avar.getText().length();
        char c = evt.getKeyChar();
        
        if(length<2)
        {
            if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
            {
              avar.setEditable(true);   
            }
            else
            {
                
                if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
                    {
                       avar.setEditable(true); 
                    }
                
                else if(Character.isLetter(c)){
                avar.setEditable(false);
                 JOptionPane p2 = new JOptionPane("only number is allowed",JOptionPane.INFORMATION_MESSAGE);
                    JDialog d = p2.createDialog("Warning");
                         d.setAlwaysOnTop(true);
                     d.setVisible(true);
                }
            }
        }
        
        else if(length>=2)
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
                    {
                       avar.setEditable(true); 
                    }
            
            else
            {
                avar.setEditable(false); 
                JOptionPane p2 = new JOptionPane("maximum 2 digit",JOptionPane.INFORMATION_MESSAGE);
                    JDialog d = p2.createDialog("Warning");
                         d.setAlwaysOnTop(true);
                     d.setVisible(true);
            }
        }
    }//GEN-LAST:event_avarKeyPressed

    private void fvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fvarKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        String name = fvar.getText();
        int length = name.length();
        
        
        if(Character.isLetter(c) || Character.isISOControl(c))
        {
            System.out.println(length);
           
            if(length<=9)
        {
            fvar.setEditable(true);
            System.out.println(length);
//            System.out.println(length);
        }
            
             else if(length>9)
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                fvar.setEditable(true);
                            System.out.println(length);

                
            }
            
            else {
            fvar.setEditable(false);
               JOptionPane p = new JOptionPane("name should be in maximum 10 letter");
                  Dialog d = p.createDialog("Warning");
                  d.setAlwaysOnTop(true);
                  d.setVisible(true);
            }
        }
//            uvar.setEditable(true);
            
        }
        
        else if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            fvar.setEditable(false);
            JOptionPane p = new JOptionPane("only letter is allowed");
                  Dialog d = p.createDialog("Warning");
                  d.setAlwaysOnTop(true);
                  d.setVisible(true);
        }
    }//GEN-LAST:event_fvarKeyPressed

    private void lvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lvarKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        String name = lvar.getText();
        int length = name.length();
        
        
        if(Character.isLetter(c) || Character.isISOControl(c))
        {
            System.out.println(length);
           
            if(length<=9)
        {
            lvar.setEditable(true);
            System.out.println(length);
//            System.out.println(length);
        }
            
             else if(length>9)
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                lvar.setEditable(true);
                            System.out.println(length);

                
            }
            
            else {
            lvar.setEditable(false);
               JOptionPane p = new JOptionPane("name should be in maximum 10 letter");
                  Dialog d = p.createDialog("Warning");
                  d.setAlwaysOnTop(true);
                  d.setVisible(true);
            }
        }
//            uvar.setEditable(true);
            
        }
        
        else if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            lvar.setEditable(false);
            JOptionPane p = new JOptionPane("only letter is allowed");
                  Dialog d = p.createDialog("Warning");
                  d.setAlwaysOnTop(true);
                  d.setVisible(true);
        }
    }//GEN-LAST:event_lvarKeyPressed

    private void gvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gvarKeyPressed
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        
        if(Character.isLetter(c) || Character.isLetter(c))
        {
            gvar.setEditable(true);
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                    gvar.setEditable(true);
            }
            else if(c>='0' && c<='9')
            {
                gvar.setEditable(false);
            }
        }
    }//GEN-LAST:event_gvarKeyPressed

    private void uvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uvarKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        String username = uvar.getText();
        int length = username.length();
        
        
        if(Character.isLetter(c) || Character.isISOControl(c) || c>='0' && c<'9')
        {
           
            if(length<=11)
        {
            uvar.setEditable(true);
//            System.out.println(length);
        }
            
             else if(length>11)
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                uvar.setEditable(true);
                
            }
            
            else{
            uvar.setEditable(false);
               JOptionPane p = new JOptionPane("username should be in maximum 12 letter");
                  Dialog d = p.createDialog("Warning");
                  d.setAlwaysOnTop(true);
                  d.setVisible(true);
            }
        }
//            uvar.setEditable(true);
            
        }
        
    }//GEN-LAST:event_uvarKeyPressed

    private void qvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qvarKeyPressed
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        
        if(Character.isLetter(c) || Character.isLetter(c))
        {
            qvar.setEditable(true);
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                    qvar.setEditable(true);
            }
            else if(c>='0' && c<='9')
            {
                qvar.setEditable(false);
            }
        }
    }//GEN-LAST:event_qvarKeyPressed

    private void gvarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gvarKeyReleased
        // TODO add your handling code here:
        String gender = gvar.getText().toUpperCase();
        gvar.setText(gender);
        
    }//GEN-LAST:event_gvarKeyReleased

    private void qvarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qvarKeyReleased
        // TODO add your handling code here:
        String qualification = qvar.getText().toUpperCase();
        qvar.setText(qualification);
    }//GEN-LAST:event_qvarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_personal_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_personal_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_personal_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_personal_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new student_personal_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField avar;
    private javax.swing.JButton editbutton;
    private javax.swing.JTextField fvar;
    private javax.swing.JTextField gvar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lvar;
    private javax.swing.JTextField qvar;
    private javax.swing.JTextField uvar;
    // End of variables declaration//GEN-END:variables
}
