/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz;

import dbconnection.connectionprovider;
import java.awt.Dialog;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author ABHISHEK TOMAR
 */
public class student_details extends javax.swing.JFrame {

    /**
     * Creates new form student_details
     */
    public student_details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        uvar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(489, 234));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("GO QUIZ");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/exit.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton4)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 423, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Student Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 158, -1, -1));

        uvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        uvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uvarActionPerformed(evt);
            }
        });
        uvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uvarKeyPressed(evt);
            }
        });
        getContentPane().add(uvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 155, 198, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/search icon.png"))); // NOI18N
        jButton2.setText("CHECK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 221, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/Clear-icon (1).png"))); // NOI18N
        jButton3.setText("CLEAR");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 221, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uvarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Admin_first_page.setvalue(0);
        setVisible(false);
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String username = "";
       username = uvar.getText();
        if(username.equals(""))
        {
             JOptionPane p2 = new JOptionPane("please enter username",JOptionPane.INFORMATION_MESSAGE);
            JDialog d2 = p2.createDialog("Message");
            d2.setAlwaysOnTop(true);
            d2.setVisible(true);
        }
        else
        {
        try
        {
        Connection con = connectionprovider.connector();
        Statement st = con.createStatement();
        
        ResultSet rs = st.executeQuery("select * from student where uname='"+username+"'");
        if(rs.next()==true)
        {
            setVisible(false);
            new Admin_first_page().setVisible(false);
            
            new student_personal_details(username).setVisible(true);
            Admin_first_page.setvalue(0);
        }
        
        else
        {
//            JOptionPane p = new JOptionPane("Wrong username");
//            JDialog d = p.createDialog("Warning");
//            d.setVisible(true);
//            d.setAlwaysOnTop(true);
            
            JOptionPane p = new JOptionPane("Wrong Username",JOptionPane.INFORMATION_MESSAGE);
            JDialog d = p.createDialog("Message");
            d.setAlwaysOnTop(true);
            d.setVisible(true);
        }
        }
        
        catch(Exception e)
                {
                    JOptionPane p = new JOptionPane("Sorry some errro has occured please check your connection");
                     JDialog d = p.createDialog("Warning");
                    d.setVisible(true);
                     d.setAlwaysOnTop(true);
                     System.out.print("error is "+e);
                }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void uvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uvarKeyPressed
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        
        String username = uvar.getText();
        int length = username.length();
        
        
        if(Character.isLetter(c) || Character.isISOControl(c) || c>='0' && c<'9')
        {
           
            if(length<=11)
        {
            uvar.setEditable(true);
//            System.out.println(length);
        }
            
             else if(length>11)
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                uvar.setEditable(true);
                
            }
            
            else{
            uvar.setEditable(false);
               JOptionPane p = new JOptionPane("username should be in maximum 12 letter");
                  Dialog d = p.createDialog("Warning");
                  d.setAlwaysOnTop(true);
                  d.setVisible(true);
            }
        }
//            uvar.setEditable(true);
            
        }
    }//GEN-LAST:event_uvarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField uvar;
    // End of variables declaration//GEN-END:variables
}
